[build]
    functions="functions/"
    publish="ui/"

[build.environment]
    GO_IMPORT_PATH="github.com/futuregerald/lambda-hydrator"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status=200
  force=true